import React from 'react';
import { MessageSquare, ChevronRight } from 'lucide-react';

const DoctorQuestions = ({ questions }) => {
  if (!questions || questions.length === 0) return null;

  return (
    <div className="glass-card p-8 rounded-2xl border-l-4 border-blue-500">
      <div className="flex items-center gap-3 mb-6">
        <div className="bg-blue-500/20 p-2 rounded-lg">
          <MessageSquare className="w-6 h-6 text-blue-500" />
        </div>
        <h3 className="text-2xl font-bold text-white uppercase tracking-tight">What to discuss with your doctor</h3>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {questions.map((q, i) => (
          <div key={i} className="bg-white/5 p-4 rounded-xl border border-white/5 hover:border-blue-500/30 transition-all flex items-start gap-3 group">
            <div className="bg-blue-500/10 text-blue-500 rounded-full w-6 h-6 flex items-center justify-center text-xs font-bold shrink-0 mt-0.5 group-hover:bg-blue-500 group-hover:text-white transition-colors">
              {i + 1}
            </div>
            <p className="text-gray-300 font-medium leading-relaxed">{q}</p>
          </div>
        ))}
      </div>
      
      <p className="text-xs text-gray-500 mt-6 italic">
        *These questions are generated by AI to help facilitate your medical consultation. They do not constitute a clinical recommendation.
      </p>
    </div>
  );
};

export default DoctorQuestions;
